### ISSUE TITLE
add languages

### ISSUE THREAD

**Issue by angelika-mamchych** [angelika-mamchych/blogmaker#8]
**Issue** 
As a user I want to change language of the site content
**Root cause**
Feature
**Implementation steps:**
- [x] add language button/link to UI
- [x] save the language to cooke (new route `/change-language/<name>/`)
- [x] alter `articles` table add  language specific columns
- [x] add language specific fields to `add article form`
- [x] get content depending on language cookie while `SELECT` from `articles`
- [x] enjoy :-)
